remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: [KSU SWE 4743 Object-Oriented Design]
tagline:
  [Kennesaw State University | College of Computing and Software Engineering]

markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
